-- 코드를 입력하세요
SELECT F.FLAVOR FROM FIRST_HALF F JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) S FROM JULY GROUP BY FLAVOR) J  ON F.FLAVOR = J.FLAVOR
GROUP BY F.FLAVOR
ORDER BY SUM(F.TOTAL_ORDER)+S DESC
LIMIT 3